### ISSUE TITLE
Where to install for searching all cPanel accounts

### ISSUE THREAD

**Issue by NellicusLabs** [MarioKnight/cPanel-wp-management#1]
Can you give a little more information about how to get this to work with scanning all accounts on a cPanel server. I have it running but I do not get a version number of the wordpress installs.

**Comment by MarioKnight** [comment]
You should be able to put the files in any folder you wish.  They're designed to be run as long as they're in the same folder.  Could you copy and paste the command you ran as well as the result?  I'm curious as to see what the error is which should help me see where the issue lies.

**Comment by NellicusLabs** [comment]
Removed the actual users and domains but this is what I am getting. 

sh  ./wp-version.sh

User: user1 / domain1.com - 
User: user2 / domain2.com - 
etc

**Comment by MarioKnight** [comment]
I was hoping to see an error, however it looks like everything is working except the reporting from WP-CLI.  Let's focus on that for now and see if we can figure out why that's not working.

`cd /home/user1/public_html/`
`wp core version --allow-root`

We should see the version number appear here, we're only using `--allow-root` for checking since we're root/su right now.  Hopefully we'll see more information.

**Comment by NellicusLabs** [comment]
It just returns me to enter another command. I am wondering if some how wp-cli is not correct. 

root@l3 [/home/user1/public_html]# wp core version --allow-root
root@l3 [/home/user1/public_html]#

root@l3 [/home/user1/public_html]# php wp-cli.phar --info
Could not open input file: wp-cli.phar
root@l3 [/home/user1/public_html]#

**Comment by MarioKnight** [comment]
That definitely appears to be something to do with WP-CLI.  When running that test command you quoted, you should see either basic info on WP-CLI, or a warning that you're running it as root.  I would try to restart WP-CLI's installation, and change the permission of the downloaded file to be safe.

`curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar`
`chmod +x wp-cli.phar`
`mv wp-cli.phar /usr/local/bin/wp`
`wp --info --allow-root`

This should make everything run just by calling wp going forward, and you should see something similar to the following:

`root@wp2 [~]# wp --info --allow-root`
`PHP binary:     /usr/local/bin/php`
`PHP version:    5.4.43`
`php.ini used:   /usr/local/lib/php.ini`
`WP-CLI root dir:        phar://wp-cli.phar`
`WP-CLI global config:`
`WP-CLI project config:`
`WP-CLI version: 0.19.2`

**Comment by NellicusLabs** [comment]
Think I got it. 
Had to add the following to my php.ini file

suhosin.executor.include.whitelist = phar

I now see the correct output

**Comment by MarioKnight** [comment]
Interesting, I don't have that in the ones on the servers I have this on.  I will note this in case someone else comes across issue in the future.  Good to hear that the correct output is seen in the test though!  Are you seeing the desired output from the scripts now that WP-CLI is working?

**Comment by NellicusLabs** [comment]
Yes. I am seeing exactly what I would expect from wp-version.sh

**Comment by MarioKnight** [comment]
Perfect!  I will close this then.  Thanks for sharing the solution to your issue, and I hope you enjoy these scripts!
